export const articles = [
  {
    slug: 'se-former-intelligence-artificielle-travail-2025',
    title: "Se former à l'intelligence artificielle au travail : guide pratique pour débuter en 2025",
    excerpt: "L'IA transforme le monde du travail. Découvrez comment vous former à l'intelligence artificielle sans être développeur, quels outils maîtriser et comment l'intégrer dans votre quotidien professionnel.",
    date: '2026-05-16',
    dateModified: '2026-05-16',
    readTime: 7,
    coverImage: '/images/default-blog-cover.jpg',
    tags: ['Intelligence Artificielle', 'Formation', 'Compétences'],
    keywords: ['formation intelligence artificielle', 'IA au travail', 'apprendre IA sans coder', 'outils IA professionnels', 'compétences IA 2025'],
  },
  {
    slug: 'cv-ats-2025',
    title: 'Comment rédiger un CV qui passe les filtres ATS en 2025 ?',
    excerpt: 'Découvrez comment optimiser votre CV pour les logiciels ATS et décrocher plus d\'entretiens en 2025. Mots-clés, structure, format : le guide complet RPAM.',
    date: '2026-05-16',
    dateModified: '2026-05-16',
    readTime: 8,
    coverImage: '/images/default-blog-cover.jpg',
    tags: ['CV', 'ATS', "Recherche d'emploi", 'Recrutement'],
    keywords: ['CV ATS', 'optimiser CV', 'logiciel recrutement ATS', 'mots-clés CV', 'recherche emploi 2025'],
  },
  {
    slug: 'reconversion-professionnelle-30-40-50-ans',
    title: 'Reconversion professionnelle à 30, 40 ou 50 ans : par où commencer en 2025 ?',
    excerpt: 'Guide complet pour réussir votre reconversion professionnelle à tout âge. Étapes clés, financements CPF, secteurs porteurs et conseils pour changer de métier avec succès.',
    date: '2025-05-11',
    dateModified: '2025-05-11',
    readTime: 10,
    coverImage: '/images/blog/reconversion-professionnelle-cover.jpg',
    tags: ['Reconversion', 'Bilan de compétences', 'CPF'],
    keywords: ['reconversion professionnelle', 'bilan de compétences', 'changement de carrière', 'CPF', 'orientation professionnelle'],
  },
]
